### ISSUE TITLE
Move MediaStreamControl business logic into Conference.tsx component

### ISSUE THREAD

**Issue by asinner** [teamious/react-conf-webrtc#105]

**Comment by ekoneko** [comment]
Why do this?

**Comment by asinner** [comment]
the problem we're facing is communication between MediaStreamControl and Conference component. When a user clicks mute audio or disable video in the MediaStreamControl component, the Conference component must be notified so that it can broadcast an event to all of the PeerConnections. Because MediaStreamControl must notify Conference component, it relies on the end user to correctly bridge the communication between the two components if they use the custom rendering feature of Conference. Since this is not ideal, we moved all of the business logic into Conference component and expose the functionality via the custom renderer. This approach eliminates the communication between MediaStreamControl and Conference since Conference provides the functionality.
