### ISSUE TITLE
Add custom rendering experience for MediaStreamControl

### ISSUE THREAD

**Issue by asinner** [teamious/react-conf-webrtc#72]
Right now we currently hardcode the UI for the `MediaStreamControl` component. We should expose an API that lets the end user provide the UI. The API should pass the `mute` and `disable` functions as arguments to the renderer function.

**Comment by ekoneko** [comment]
I'm not very clearly.

In this [demo](https://github.com/teamious/react-conf-webrtc/blob/master/docs/src/components/App.tsx),  we can replace the `render` method of `Conference` component, and call `MediaStreamControl` by self.

The `MediaStreamControl` component get a stream prop and execute the mute or disable on it.

So, I think users can replace the render of `Conference` component, get stream instance, and set mute or disable by themselves directly without `MediaStreamControl` if they want a custom UI?

PS, I'm a FE engineer in Beijing Jingoal,inc. Glad to join the project :)

**Comment by asinner** [comment]
Hi @ekoneko,

Thanks for joining the project.

You are correct, they can do that. However, we want to encapsulate the business logic for this behavior in a component. Adding a `render` API (similar to `Conference`) allows the user to specify the UI and not rewrite the business logic.

**Comment by ekoneko** [comment]
Ok, thanks replied, I got the reason and have some more uncertainty question about the code design.

I think users need to get the current state about muted, disabled or more we may add later and set them true or false.

Every state we need define two methods like this?

````tsx
export interface IMediaStreamControlHandle {
    getDisable: () => boolean;
    setDisable: (disable: boolean) => void;
    getMute: () => boolean;
    setMute: (mute: boolean) => void;
    // or more in future
}

export interface IMediaStreamControlRenderer {
    (handle: IMediaStreamControlHandle): JSX.Element | null | false;
}
````

Or define a unified getter / setter like:

(It's simple, but users may not get clearly without ts declare)

````tsx
get(name: IAttributeName): any
set(name: IAttributeName, state:any): void
````

**Comment by asinner** [comment]
Yes, that is correct. But I would not use a unified setter / getter because it loses type information.
